export * from './BusinessBold';
export * from './WalletBold';
export * from './CheckCircle';
export * from './Ellipse';
export * from './ErrorFilled';
export * from './FrontDoc';
export * from './BackDoc';
export * from './Upload';
export * from './FileEdit';
export * from './FaceValid'
export * from './Folder'
export * from './Law'
export * from './Terms'
export * from './Search'