export const COUNTRIES = [
    { name: "Afganistán" },
    { name: "Albania" },
    { name: "Alemania" },
    { name: "Andorra" },
    { name: "Angola" },
    { name: "Antigua y Barbuda" },
    { name: "Arabia Saudita" },
    { name: "Argelia" },
    { name: "Argentina" },
    { name: "Armenia" },
    { name: "Australia" },
    { name: "Austria" },
    { name: "Azerbaiyán" },
    { name: "Bahamas" },
    { name: "Bangladés" },
    { name: "Barbados" },
    { name: "Baréin" },
    { name: "Bélgica" },
    { name: "Belice" },
    { name: "Benín" },
    { name: "Bielorrusia" },
    { name: "Birmania" },
    { name: "Bolivia" },
    { name: "Bosnia y Herzegovina" },
    { name: "Botsuana" },
    { name: "Brasil" },
    { name: "Brunéi" },
    { name: "Bulgaria" },
    { name: "Burkina Faso" },
    { name: "Burundi" },
    { name: "Bután" },
    { name: "Cabo Verde" },
    { name: "Camboya" },
    { name: "Camerún" },
    { name: "Canadá" },
    { name: "Catar" },
    { name: "Chad" },
    { name: "Chile" },
    { name: "China" },
    { name: "Chipre" },
    { name: "Ciudad del Vaticano" },
    {
        name: "Colombia",
        departments: [
            {
                name: "Amazonas",
                city: [
                    "LETICIA",
                    "EL ENCANTO",
                    "LA CHORRERA",
                    "LA PEDRERA",
                    "LA VICTORIA",
                    "MIRITI - PARANA",
                    "PUERTO ALEGRIA",
                    "PUERTO ARICA",
                    "PUERTO NARIÑO",
                    "PUERTO SANTANDER",
                    "TARAPACA"
                ]
            },
            {
                name: "Antioquía",
                city: [
                    "MEDELLIN",
                    "ABEJORRAL",
                    "ABRIAQUI",
                    "ALEJANDRIA",
                    "AMAGA",
                    "AMALFI",
                    "ANDES",
                    "ANGELOPOLIS",
                    "ANGOSTURA",
                    "ANORI",
                    "SANTAFE DE ANTIOQUIA",
                    "ANZA",
                    "APARTADO",
                    "ARBOLETES",
                    "ARGELIA",
                    "ARMENIA",
                    "BARBOSA",
                    "BELMIRA",
                    "BELLO",
                    "BETANIA",
                    "BETULIA",
                    "CIUDAD BOLIVAR",
                    "BRICEÑO",
                    "BURITICA",
                    "CACERES",
                    "CAICEDO",
                    "CALDAS",
                    "CAMPAMENTO",
                    "CAÑASGORDAS",
                    "CARACOLI",
                    "CARAMANTA",
                    "CAREPA",
                    "CARMEN DE VIBORAL",
                    "CAROLINA",
                    "CAUCASIA",
                    "CHIGORODO",
                    "CISNEROS",
                    "COCORNA",
                    "CONCEPCION",
                    "CONCORDIA",
                    "COPACABANA",
                    "DABEIBA",
                    "DON MATIAS",
                    "EBEJICO",
                    "EL BAGRE",
                    "ENTRERRIOS",
                    "ENVIGADO",
                    "FREDONIA",
                    "FRONTINO",
                    "GIRALDO",
                    "GIRARDOTA",
                    "GOMEZ PLATA",
                    "GRANADA",
                    "GUADALUPE",
                    "GUARNE",
                    "GUATAPE",
                    "HELICONIA",
                    "HISPANIA",
                    "ITAGUI",
                    "ITUANGO",
                    "JARDIN",
                    "JERICO",
                    "LA CEJA",
                    "LA ESTRELLA",
                    "LA PINTADA",
                    "LA UNION",
                    "LIBORINA",
                    "MACEO",
                    "MARINILLA",
                    "MONTEBELLO",
                    "MURINDO",
                    "MUTATA",
                    "NARIÑO",
                    "NECOCLI",
                    "NECHI",
                    "OLAYA",
                    "PEÑOL",
                    "PEQUE",
                    "PUEBLORRICO",
                    "PUERTO BERRIO",
                    "PUERTO NARE",
                    "PUERTO TRIUNFO",
                    "REMEDIOS",
                    "RETIRO",
                    "RIONEGRO",
                    "SABANALARGA",
                    "SABANETA",
                    "SALGAR",
                    "SAN ANDRES",
                    "SAN CARLOS",
                    "SAN FRANCISCO",
                    "SAN JERONIMO",
                    "SAN JOSE DE LA MONTAÑA",
                    "SAN JUAN DE URABA",
                    "SAN LUIS",
                    "SAN PEDRO",
                    "SAN PEDRO DE URABA",
                    "SAN RAFAEL",
                    "SAN ROQUE",
                    "SAN VICENTE",
                    "SANTA BARBARA",
                    "SANTA ROSA DE OSOS",
                    "SANTO DOMINGO",
                    "SANTUARIO",
                    "SEGOVIA",
                    "SONSON",
                    "SOPETRAN",
                    "TAMESIS",
                    "TARAZA",
                    "TARSO",
                    "TITIRIBI",
                    "TOLEDO",
                    "TURBO",
                    "URAMITA",
                    "URRAO",
                    "VALDIVIA",
                    "VALPARAISO",
                    "VEGACHI",
                    "VENECIA",
                    "VIGIA DEL FUERTE",
                    "YALI",
                    "YARUMAL",
                    "YOLOMBO",
                    "YONDO",
                    "ZARAGOZA"
                ]
            },
            {
                name: "Arauca",
                city: [
                    "ARAUCA",
                    "ARAUQUITA",
                    "CRAVO NORTE",
                    "FORTUL",
                    "PUERTO RONDON",
                    "SARAVENA",
                    "TAME"
                ]
            },
            {
                name: "Atlántico",
                city: [
                    "BARRANQUILLA",
                    "BARANOA",
                    "CAMPO DE LA CRUZ",
                    "CANDELARIA",
                    "GALAPA",
                    "JUAN DE ACOSTA",
                    "LURUACO",
                    "MALAMBO",
                    "MANATI",
                    "PALMAR DE VARELA",
                    "PIOJO",
                    "POLONUEVO",
                    "PONEDERA",
                    "PUERTO COLOMBIA",
                    "REPELON",
                    "SABANAGRANDE",
                    "SABANALARGA",
                    "SANTA LUCIA",
                    "SANTO TOMAS",
                    "SOLEDAD",
                    "SUAN",
                    "TUBARA",
                    "USIACURI"
                ]
            },
            {
                name: "Bolívar",
                city: [
                    "CARTAGENA",
                    "ACHI",
                    "ALTOS DEL ROSARIO",
                    "ARENAL",
                    "ARJONA",
                    "ARROYOHONDO",
                    "BARRANCO DE LOBA",
                    "CALAMAR",
                    "CANTAGALLO",
                    "CICUCO",
                    "CORDOBA",
                    "CLEMENCIA",
                    "EL CARMEN DE BOLIVAR",
                    "EL GUAMO",
                    "EL PEÑON",
                    "HATILLO DE LOBA",
                    "MAGANGUE",
                    "MAHATES",
                    "MARGARITA",
                    "MARIA LA BAJA",
                    "MONTECRISTO",
                    "MOMPOS",
                    "MORALES",
                    "NOROSI",
                    "PINILLOS",
                    "REGIDOR",
                    "RIO VIEJO",
                    "SAN CRISTOBAL",
                    "SAN ESTANISLAO",
                    "SAN FERNANDO",
                    "SAN JACINTO",
                    "SAN JACINTO DEL CAUCA",
                    "SAN JUAN NEPOMUCENO",
                    "SAN MARTIN DE LOBA",
                    "SAN PABLO",
                    "SANTA CATALINA",
                    "SANTA ROSA",
                    "SANTA ROSA DEL SUR",
                    "SIMITI",
                    "SOPLAVIENTO",
                    "TALAIGUA NUEVO",
                    "TIQUISIO",
                    "TURBACO",
                    "TURBANA",
                    "VILLANUEVA",
                    "ZAMBRANO"
                ]
            },
            {
                name: "Boyacá",
                city: [
                    "TUNJA",
                    "ALMEIDA",
                    "AQUITANIA",
                    "ARCABUCO",
                    "BELEN",
                    "BERBEO",
                    "BETEITIVA",
                    "BOAVITA",
                    "BOYACA",
                    "BRICEÑO",
                    "BUENAVISTA",
                    "BUSBANZA",
                    "CALDAS",
                    "CAMPOHERMOSO",
                    "CERINZA",
                    "CHINAVITA",
                    "CHIQUINQUIRA",
                    "CHISCAS",
                    "CHITA",
                    "CHITARAQUE",
                    "CHIVATA",
                    "CIENEGA",
                    "COMBITA",
                    "COPER",
                    "CORRALES",
                    "COVARACHIA",
                    "CUBARA",
                    "CUCAITA",
                    "CUITIVA",
                    "CHIQUIZA",
                    "CHIVOR",
                    "DUITAMA",
                    "EL COCUY",
                    "EL ESPINO",
                    "FIRAVITOBA",
                    "FLORESTA",
                    "GACHANTIVA",
                    "GAMEZA",
                    "GARAGOA",
                    "GUACAMAYAS",
                    "GUATEQUE",
                    "GUAYATA",
                    "GUICAN",
                    "IZA",
                    "JENESANO",
                    "JERICO",
                    "LABRANZAGRANDE",
                    "LA CAPILLA",
                    "LA VICTORIA",
                    "LA UVITA",
                    "VILLA DE LEYVA",
                    "MACANAL",
                    "MARIPI",
                    "MIRAFLORES",
                    "MONGUA",
                    "MONGUI",
                    "MONIQUIRA",
                    "MOTAVITA",
                    "MUZO",
                    "NOBSA",
                    "NUEVO COLON",
                    "OICATA",
                    "OTANCHE",
                    "PACHAVITA",
                    "PAEZ",
                    "PAIPA",
                    "PAJARITO",
                    "PANQUEBA",
                    "PAUNA",
                    "PAYA",
                    "PAZ DE RIO",
                    "PESCA",
                    "PISBA",
                    "PUERTO BOYACA",
                    "QUIPAMA",
                    "RAMIRIQUI",
                    "RAQUIRA",
                    "RONDON",
                    "SABOYA",
                    "SACHICA",
                    "SAMACA",
                    "SAN EDUARDO",
                    "SAN JOSE DE PARE",
                    "SAN LUIS DE GACENO",
                    "SAN MATEO",
                    "SAN MIGUEL DE SEMA",
                    "SAN PABLO BORBUR",
                    "SANTANA",
                    "SANTA MARIA",
                    "SAN ROSA VITERBO",
                    "SANTA SOFIA",
                    "SATIVANORTE",
                    "SATIVASUR",
                    "SIACHOQUE",
                    "SOATA",
                    "SOCOTA",
                    "SOCHA",
                    "SOGAMOSO",
                    "SOMONDOCO",
                    "SORA",
                    "SOTAQUIRA",
                    "SORACA",
                    "SUSACON",
                    "SUTAMARCHAN",
                    "SUTATENZA",
                    "TASCO",
                    "TENZA",
                    "TIBANA",
                    "TIBASOSA",
                    "TINJACA",
                    "TIPACOQUE",
                    "TOCA",
                    "TOGUI",
                    "TOPAGA",
                    "TOTA",
                    "TUNUNGUA",
                    "TURMEQUE",
                    "TUTA",
                    "TUTAZA",
                    "UMBITA",
                    "VENTAQUEMADA",
                    "VIRACACHA",
                    "ZETAQUIRA"
                ]
            },
            {
                name: "Caldas",
                city: [
                    "MANIZALES",
                    "AGUADAS",
                    "ANSERMA",
                    "ARANZAZU",
                    "BELALCAZAR",
                    "CHINCHINA",
                    "FILADELFIA",
                    "LA DORADA",
                    "LA MERCED",
                    "MANZANARES",
                    "MARMATO",
                    "MARQUETALIA",
                    "MARULANDA",
                    "NEIRA",
                    "NORCASIA",
                    "PACORA",
                    "PALESTINA",
                    "PENSILVANIA",
                    "RIOSUCIO",
                    "RISARALDA",
                    "SALAMINA",
                    "SAMANA",
                    "SAN JOSE",
                    "SUPIA",
                    "VICTORIA",
                    "VILLAMARIA",
                    "VITERBO"
                ]
            },
            {
                name: "Caquetá",
                city: [
                    "FLORENCIA",
                    "ALBANIA",
                    "BELEN DE LOS ANDAQUIES",
                    "CARTAGENA DEL CHAIRA",
                    "CURRILLO",
                    "EL DONCELLO",
                    "EL PAUJIL",
                    "LA MONTAÑITA",
                    "MILAN",
                    "MORELIA",
                    "PUERTO RICO",
                    "SAN JOSE DEL FRAGUA",
                    "SAN VICENTE DEL CAGUAN",
                    "SOLANO",
                    "SOLITA",
                    "VALPARAISO"
                ]
            },
            {
                name: "Casanare",
                city: [
                    "YOPAL",
                    "AGUAZUL",
                    "CHAMEZA",
                    "HATO COROZAL",
                    "LA SALINA",
                    "MANI",
                    "MONTERREY",
                    "NUNCHIA",
                    "OROCUE",
                    "PAZ DE ARIPORO",
                    "PORE",
                    "RECETOR",
                    "SABANALARGA",
                    "SACAMA",
                    "SAN LUIS DE PALENQUE",
                    "TAMARA",
                    "TAURAMENA",
                    "TRINIDAD",
                    "VILLANUEVA"
                ]
            },
            {
                name: "Cauca",
                city: [
                    "POPAYAN",
                    "ALMAGUER",
                    "ARGELIA",
                    "BALBOA",
                    "BOLIVAR",
                    "BUENOS AIRES",
                    "CAJIBIO",
                    "CALDONO",
                    "CALOTO",
                    "CORINTO",
                    "EL TAMBO",
                    "FLORENCIA",
                    "GUACHENE",
                    "GUAPI",
                    "INZA",
                    "JAMBALO",
                    "LA SIERRA",
                    "LA VEGA",
                    "LOPEZ",
                    "MERCADERES",
                    "MIRANDA",
                    "MORALES",
                    "PADILLA",
                    "PAEZ",
                    "PATIA",
                    "PIAMONTE",
                    "PIENDAMO",
                    "PUERTO TEJADA",
                    "PURACE",
                    "ROSAS",
                    "SAN SEBASTIAN",
                    "SANTANDER DE QUILICHAO",
                    "SANTA ROSA",
                    "SILVIA",
                    "SOTARA",
                    "SUAREZ",
                    "SUCRE",
                    "TIMBIO",
                    "TIMBIQUI",
                    "TORIBIO",
                    "TOTORO",
                    "VILLA RICA"
                ]
            },
            {
                name: "Cesar",
                city: [
                    "VALLEDUPAR",
                    "AGUACHICA",
                    "AGUSTIN CODAZZI",
                    "ASTREA",
                    "BECERRIL",
                    "BOSCONIA",
                    "CHIMICHAGUA",
                    "CHIRIGUANA",
                    "CURUMANI",
                    "EL COPEY",
                    "EL PASO",
                    "GAMARRA",
                    "GONZALEZ",
                    "LA GLORIA",
                    "LA JAGUA DE IBIRICO",
                    "MANAURE",
                    "PAILITAS",
                    "PELAYA",
                    "PUEBLO BELLO",
                    "RIO DE ORO",
                    "LA PAZ",
                    "SAN ALBERTO",
                    "SAN DIEGO",
                    "SAN MARTIN",
                    "TAMALAMEQUE"
                ]
            },
            {
                name: "Chocó",
                city: [
                    "QUIBDO",
                    "ACANDI",
                    "ALTO BAUDO",
                    "ATRATO",
                    "BAGADO",
                    "BAHIA SOLANO",
                    "BAJO BAUDO",
                    "BOJAYA",
                    "CANTON DE SAN PABLO",
                    "CARMEN DEL DARIEN",
                    "CERTEGUI",
                    "CONDOTO",
                    "EL CARMEN DE ATRATO",
                    "EL LITORAL DEL SAN JUAN",
                    "ITSMINA",
                    "JURADO",
                    "LLORO",
                    "MEDIO ATRATO",
                    "MEDIO BAUDÓ",
                    "MEDIO SAN JUAN",
                    "NOVITA",
                    "NUQUI",
                    "RIO IRO",
                    "RIO QUITO",
                    "RIOSUCIO",
                    "SAN JOSE DEL PALMAR",
                    "SIPI",
                    "TADO",
                    "UNGUIA",
                    "UNION PANAMERICANA"
                ]
            },
            {
                name: "Córdoba",
                city: [
                    "MONTERIA",
                    "AYAPEL",
                    "BUENAVISTA",
                    "CANALETE",
                    "CERETE",
                    "CHIMA",
                    "CHINU",
                    "CIENAGA DE ORO",
                    "COTORRA",
                    "LA APARTADA",
                    "LORICA",
                    "LOS CORDOBAS",
                    "MOMIL",
                    "MONTELIBANO",
                    "MOÑITOS",
                    "PLANETA RICA",
                    "PUEBLO NUEVO",
                    "PUERTO ESCONDIDO",
                    "PUERTO LIBERTADOR",
                    "PURISIMA",
                    "SAHAGUN",
                    "SAN ANDRES SOTAVENTO",
                    "SAN ANTERO",
                    "SAN BERNARDO DEL VIENTO",
                    "SAN CARLOS",
                    "SAN JOSE DE URE",
                    "SAN PELAYO",
                    "TIERRALTA",
                    "TUCHIN",
                    "VALENCIA"
                ]
            },
            {
                name: "Cundinamarca",
                city: [
                    "AGUA DE DIOS",
                    "ALBAN",
                    "ANAPOIMA",
                    "ANOLAIMA",
                    "ARBELAEZ",
                    "BELTRAN",
                    "BITUIMA",
                    "BOJACA",
                    "BOGOTÁ D.C",
                    "CABRERA",
                    "CACHIPAY",
                    "CAJICA",
                    "CAPARRAPI",
                    "CAQUEZA",
                    "CARMEN DE CARUPA",
                    "CHAGUANI",
                    "CHIA",
                    "CHIPAQUE",
                    "CHOACHI",
                    "CHOCONTA",
                    "COGUA",
                    "COTA",
                    "CUCUNUBA",
                    "EL COLEGIO",
                    "EL PEÑON",
                    "EL ROSAL",
                    "FACATATIVA",
                    "FOMEQUE",
                    "FOSCA",
                    "FUNZA",
                    "FUQUENE",
                    "FUSAGASUGA",
                    "GACHALA",
                    "GACHANCIPA",
                    "GACHETA",
                    "GAMA",
                    "GIRARDOT",
                    "GRANADA",
                    "GUACHETA",
                    "GUADUAS",
                    "GUASCA",
                    "GUATAQUI",
                    "GUATAVITA",
                    "GUAYABAL DE SIQUIMA",
                    "GUAYABETAL",
                    "GUTIERREZ",
                    "JERUSALEN",
                    "JUNIN",
                    "LA CALERA",
                    "LA MESA",
                    "LA PALMA",
                    "LA PEÑA",
                    "LA VEGA",
                    "LENGUAZAQUE",
                    "MACHETA",
                    "MADRID",
                    "MANTA",
                    "MEDINA",
                    "MOSQUERA",
                    "NARIÑO",
                    "NEMOCON",
                    "NILO",
                    "NIMAIMA",
                    "NOCAIMA",
                    "VENECIA",
                    "PACHO",
                    "PAIME",
                    "PANDI",
                    "PARATEBUENO",
                    "PASCA",
                    "PUERTO SALGAR",
                    "PULI",
                    "QUEBRADANEGRA",
                    "QUETAME",
                    "QUIPILE",
                    "APULO",
                    "RICAURTE",
                    "SAN ANTONIO DE TEQUENDAMA",
                    "SAN BERNARDO",
                    "SAN CAYETANO",
                    "SAN FRANCISCO",
                    "SAN JUAN DE RIO SECO",
                    "SASAIMA",
                    "SESQUILE",
                    "SIBATE",
                    "SILVANIA",
                    "SIMIJACA",
                    "SOACHA",
                    "SOPO",
                    "SUBACHOQUE",
                    "SUESCA",
                    "SUPATA",
                    "SUSA",
                    "SUTATAUSA",
                    "TABIO",
                    "TAUSA",
                    "TENA",
                    "TENJO",
                    "TIBACUY",
                    "TIBIRITA",
                    "TOCAIMA",
                    "TOCANCIPA",
                    "TOPAIPI",
                    "UBALA",
                    "UBAQUE",
                    "UBATE",
                    "UNE",
                    "UTICA",
                    "VERGARA",
                    "VIANI",
                    "VILLAGOMEZ",
                    "VILLAPINZON",
                    "VILLETA",
                    "VIOTA",
                    "YACOPI",
                    "ZIPACON",
                    "ZIPAQUIRA"
                ]
            },
            {
                name: "Guainía",
                city: [
                    "INIRIDA",
                    "BARRANCOMINAS",
                    "MAPIRIPANA",
                    "SAN FELIPE",
                    "PUERTO COLOMBIA",
                    "LA GUADALUPE",
                    "CACAHUAL",
                    "PANA PANA",
                    "MORICHAL"
                ]
            },
            {
                name: "Guaviare",
                city: [
                    "SAN JOSE DEL GUAVIARE",
                    "CALAMAR",
                    "EL RETORNO",
                    "MIRAFLORES"
                ]
            },
            {
                name: "Huila",
                city: [
                    "NEIVA",
                    "ACEVEDO",
                    "AGRADO",
                    "AIPE",
                    "ALGECIRAS",
                    "ALTAMIRA",
                    "BARAYA",
                    "CAMPOALEGRE",
                    "COLOMBIA",
                    "ELIAS",
                    "GARZON",
                    "GIGANTE",
                    "GUADALUPE",
                    "HOBO",
                    "IQUIRA",
                    "ISNOS",
                    "LA ARGENTINA",
                    "LA PLATA",
                    "NATAGA",
                    "OPORAPA",
                    "PAICOL",
                    "PALERMO",
                    "PALESTINA",
                    "PITAL",
                    "PITALITO",
                    "RIVERA",
                    "SALADOBLANCO",
                    "SAN AGUSTIN",
                    "SANTA MARIA",
                    "SUAZA",
                    "TARQUI",
                    "TESALIA",
                    "TELLO",
                    "TERUEL",
                    "TIMANA",
                    "VILLAVIEJA",
                    "YAGUARA"
                ]
            },
            {
                name: "La Guajira",
                city: [
                    "RIOHACHA",
                    "ALBANIA",
                    "BARRANCAS",
                    "DIBULLA",
                    "DISTRACCION",
                    "EL MOLINO",
                    "FONSECA",
                    "HATONUEVO",
                    "LA JAGUA DEL PILAR",
                    "MAICAO",
                    "MANAURE",
                    "SAN JUAN DEL CESAR",
                    "URIBIA",
                    "URUMITA",
                    "VILLANUEVA"
                ]
            },
            {
                name: "Magdalena",
                city: [
                    "SANTA MARTA",
                    "ALGARROBO",
                    "ARACATACA",
                    "ARIGUANI",
                    "CERRO SAN ANTONIO",
                    "CHIVOLO",
                    "CIENAGA",
                    "CONCORDIA",
                    "EL BANCO",
                    "EL PIÑON",
                    "EL RETEN",
                    "FUNDACION",
                    "GUAMAL",
                    "NUEVA GRANADA",
                    "PEDRAZA",
                    "PIJIÑO DEL CARMEN",
                    "PIVIJAY",
                    "PLATO",
                    "PUEBLOVIEJO",
                    "REMOLINO",
                    "SABANAS DE SAN ANGEL",
                    "SALAMINA",
                    "SAN SEBASTIAN DE BUENAVISTA",
                    "SAN ZENON",
                    "SANTA ANA",
                    "SANTA BARBARA DE PINTO",
                    "SITIONUEVO",
                    "TENERIFE",
                    "ZAPAYAN",
                    "ZONA BANANERA"
                ]
            },
            {
                name: "Meta",
                city: [
                    "VILLAVICENCIO",
                    "ACACIAS",
                    "BARRANCA DE UPIA",
                    "CABUYARO",
                    "CASTILLA LA NUEVA",
                    "CUBARRAL",
                    "CUMARAL",
                    "EL CALVARIO",
                    "EL CASTILLO",
                    "EL DORADO",
                    "FUENTE DE ORO",
                    "GRANADA",
                    "GUAMAL",
                    "MAPIRIPAN",
                    "MESETAS",
                    "LA MACARENA",
                    "LA URIBE",
                    "LEJANIAS",
                    "PUERTO CONCORDIA",
                    "PUERTO GAITAN",
                    "PUERTO LOPEZ",
                    "PUERTO LLERAS",
                    "PUERTO RICO",
                    "RESTREPO",
                    "SAN CARLOS GUAROA",
                    "SAN JUAN DE ARAMA",
                    "SAN JUANITO",
                    "SAN MARTIN",
                    "VISTA HERMOSA"
                ]
            },
            {
                name: "Nariño",
                city: [
                    "PASTO",
                    "ALBAN",
                    "ALDANA",
                    "ANCUYA",
                    "ARBOLEDA",
                    "BARBACOAS",
                    "BELEN",
                    "BUESACO",
                    "COLON",
                    "CONSACA",
                    "CONTADERO",
                    "CORDOBA",
                    "CUASPUD",
                    "CUMBAL",
                    "CUMBITARA",
                    "CHACHAGUI",
                    "EL CHARCO",
                    "EL PEÑOL",
                    "EL ROSARIO",
                    "EL TABLON DE GOMEZ",
                    "EL TAMBO",
                    "FUNES",
                    "GUACHUCAL",
                    "GUAITARILLA",
                    "GUALMATAN",
                    "ILES",
                    "IMUES",
                    "IPIALES",
                    "LA CRUZ",
                    "LA FLORIDA",
                    "LA LLANADA",
                    "LA TOLA",
                    "LA UNION",
                    "LEIVA",
                    "LINARES",
                    "LOS ANDES",
                    "MAGUI",
                    "MALLAMA",
                    "MOSQUERA",
                    "NARIÑO",
                    "OLAYA HERRERA",
                    "OSPINA",
                    "FRANCISCO PIZARRO",
                    "POLICARPA",
                    "POTOSI",
                    "PROVIDENCIA",
                    "PUERRES",
                    "PUPIALES",
                    "RICAURTE",
                    "ROBERTO PAYAN",
                    "SAMANIEGO",
                    "SANDONA",
                    "SAN BERNARDO",
                    "SAN LORENZO",
                    "SAN PABLO",
                    "SAN PEDRO DE CARTAGO",
                    "SANTA BARBARA",
                    "SANTACRUZ",
                    "SAPUYES",
                    "TAMINANGO",
                    "TANGUA",
                    "TUMACO",
                    "TUQUERRES",
                    "YACUANQUER"
                ]
            },
            {
                name: "Norte de Santander",
                city: [
                    "CUCUTA",
                    "ABREGO",
                    "ARBOLEDAS",
                    "BOCHALEMA",
                    "BUCARASICA",
                    "CACOTA",
                    "CACHIRA",
                    "CHINACOTA",
                    "CHITAGA",
                    "CONVENCION",
                    "CUCUTILLA",
                    "DURANIA",
                    "EL CARMEN",
                    "EL TARRA",
                    "EL ZULIA",
                    "GRAMALOTE",
                    "HACARI",
                    "HERRAN",
                    "LABATECA",
                    "LA ESPERANZA",
                    "LA PLAYA",
                    "LOS PATIOS",
                    "LOURDES",
                    "MUTISCUA",
                    "OCAÑA",
                    "PAMPLONA",
                    "PAMPLONITA",
                    "PUERTO SANTANDER",
                    "RAGONVALIA",
                    "SALAZAR",
                    "SAN CALIXTO",
                    "SAN CAYETANO",
                    "SANTIAGO",
                    "SARDINATA",
                    "SILOS",
                    "TEORAMA",
                    "TIBU",
                    "TOLEDO",
                    "VILLA CARO",
                    "VILLA DEL ROSARIO"
                ]
            },
            {
                name: "Putumayo",
                city: [
                    "MOCOA",
                    "COLON",
                    "ORITO",
                    "PUERTO ASIS",
                    "PUERTO CAICEDO",
                    "PUERTO GUZMAN",
                    "LEGUIZAMO",
                    "SIBUNDOY",
                    "SAN FRANCISCO",
                    "SAN MIGUEL",
                    "SANTIAGO",
                    "VALLE DEL GUAMUEZ",
                    "VILLAGARZON"
                ]
            },
            {
                name: "Quindío",
                city: [
                    "ARMENIA",
                    "BUENAVISTA",
                    "CALARCÁ",
                    "CIRCASIA",
                    "CÓRDOBA",
                    "FILANDIA",
                    "GÉNOVA",
                    "LA TEBAIDA",
                    "MONTENEGRO",
                    "PIJAO",
                    "QUIMBAYA",
                    "SALENTO"
                ]
            },
            {
                name: "Risaralda: Pereira",
                city: [
                    "PEREIRA",
                    "APIA",
                    "BALBOA",
                    "BELEN DE UMBRIA",
                    "DOS QUEBRADAS",
                    "GUATICA",
                    "LA CELIA",
                    "LA VIRGINIA",
                    "MARSELLA",
                    "MISTRATO",
                    "PUEBLO RICO",
                    "QUINCHIA",
                    "SANTA ROSA DE CABAL",
                    "SANTUARIO"
                ]
            },
            {
                name: "San Andrés y Providencia",
                city: [
                    "SAN ANDRES",
                    "PROVIDENCIA"
                ]
            },
            {
                name: "Santander",
                city: [
                    "BUCARAMANGA",
                    "AGUADA",
                    "ALBANIA",
                    "ARATOCA",
                    "BARBOSA",
                    "BARICHARA",
                    "BARRANCABERMEJA",
                    "BETULIA",
                    "BOLIVAR",
                    "CABRERA",
                    "CALIFORNIA",
                    "CAPITANEJO",
                    "CARCASI",
                    "CEPITA",
                    "CERRITO",
                    "CHARALA",
                    "CHARTA",
                    "CHIMA",
                    "CHIPATA",
                    "CIMITARRA",
                    "CONCEPCION",
                    "CONFINES",
                    "CONTRATACION",
                    "COROMORO",
                    "CURITI",
                    "EL CARMEN DE CHUCURI",
                    "EL GUACAMAYO",
                    "EL PEÑON",
                    "EL PLAYON",
                    "ENCINO",
                    "ENCISO",
                    "FLORIAN",
                    "FLORIDABLANCA",
                    "GALAN",
                    "GAMBITA",
                    "GIRON",
                    "GUACA",
                    "GUADALUPE",
                    "GUAPOTA",
                    "GUAVATA",
                    "GUEPSA",
                    "HATO",
                    "JESUS MARIA",
                    "JORDAN",
                    "LA BELLEZA",
                    "LANDAZURI",
                    "LA PAZ",
                    "LEBRIJA",
                    "LOS SANTOS",
                    "MACARAVITA",
                    "MALAGA",
                    "MATANZA",
                    "MOGOTES",
                    "MOLAGAVITA",
                    "OCAMONTE",
                    "OIBA",
                    "ONZAGA",
                    "PALMAR",
                    "PALMAS DEL SOCORRO",
                    "PARAMO",
                    "PIEDECUESTA",
                    "PINCHOTE",
                    "PUENTE NACIONAL",
                    "PUERTO PARRA",
                    "PUERTO WILCHES",
                    "RIONEGRO",
                    "SABANA DE TORRES",
                    "SAN ANDRES",
                    "SAN BENITO",
                    "SAN GIL",
                    "SAN JOAQUIN",
                    "SAN JOSE DE MIRANDA",
                    "SAN MIGUEL",
                    "SAN VICENTE DE CHUCURI",
                    "SANTA BARBARA",
                    "SANTA HELENA DEL OPON",
                    "SIMACOTA",
                    "SOCORRO",
                    "SUAITA",
                    "SUCRE",
                    "SURATA",
                    "TONA",
                    "VALLE DE SAN JOSE",
                    "VELEZ",
                    "VETAS",
                    "VILLANUEVA",
                    "ZAPATOCA"
                ]
            },
            {
                name: "Sucre",
                city: [
                    "SINCELEJO",
                    "BUENAVISTA",
                    "CAIMITO",
                    "COLOSO",
                    "COROZAL",
                    "COVEÑAS",
                    "CHALAN",
                    "EL ROBLE",
                    "GALERAS",
                    "GUARANDA",
                    "LA UNION",
                    "LOS PALMITOS",
                    "MAJAGUAL",
                    "MORROA",
                    "OVEJAS",
                    "PALMITO",
                    "SAMPUES",
                    "SAN BENITO ABAD",
                    "SAN JUAN BETULIA",
                    "SAN MARCOS",
                    "SAN ONOFRE",
                    "SAN PEDRO",
                    "SINCE",
                    "SUCRE",
                    "SANTIAGO DE TOLU",
                    "TOLU VIEJO"
                ]
            },
            {
                name: "Tolima",
                city: [
                    "IBAGUÉ",
                    "ALPUJARRA",
                    "ALVARADO",
                    "AMBALEMA",
                    "ANZOÁTEGUI",
                    "ARMERO",
                    "ATACO",
                    "CAJAMARCA",
                    "CARMEN DE APICALÁ",
                    "CASABIANCA",
                    "CHAPARRAL",
                    "COELLO",
                    "COYAIMA",
                    "CUNDAY",
                    "DOLORES",
                    "ESPINAL",
                    "FALAN",
                    "FLANDES",
                    "FRESNO",
                    "GUAMO",
                    "HERVEO",
                    "HONDA",
                    "ICONONZO",
                    "LÉRIDA",
                    "LÍBANO",
                    "MARIQUITA",
                    "MELGAR",
                    "MURILLO",
                    "NATAGAIMA",
                    "ORTEGA",
                    "PALOCABILDO",
                    "PIEDRAS",
                    "PLANADAS",
                    "PRADO",
                    "PURIFICACIÓN",
                    "RIOBLANCO",
                    "RONCESVALLES",
                    "ROVIRA",
                    "SALDAÑA",
                    "SAN ANTONIO",
                    "SAN LUIS",
                    "SANTA ISABEL",
                    "SUÁREZ",
                    "VALLE DE SAN JUAN",
                    "VENADILLO",
                    "VILLAHERMOSA",
                    "VILLARRICA"
                ]
            },
            {
                name: "Valle del Cauca",
                city: [
                    "CALI",
                    "ALCALA",
                    "ANDALUCIA",
                    "ANSERMANUEVO",
                    "ARGELIA",
                    "BOLIVAR",
                    "BUENAVENTURA",
                    "BUGA",
                    "BUGALAGRANDE",
                    "CAICEDONIA",
                    "CALIMA",
                    "CANDELARIA",
                    "CARTAGO",
                    "DAGUA",
                    "EL AGUILA",
                    "EL CAIRO",
                    "EL CERRITO",
                    "EL DOVIO",
                    "FLORIDA",
                    "GINEBRA",
                    "GUACARI",
                    "JAMUNDI",
                    "LA CUMBRE",
                    "LA UNION",
                    "LA VICTORIA",
                    "OBANDO",
                    "PALMIRA",
                    "PRADERA",
                    "RESTREPO",
                    "RIOFRIO",
                    "ROLDANILLO",
                    "SAN PEDRO",
                    "SEVILLA",
                    "TORO",
                    "TRUJILLO",
                    "TULUA",
                    "ULLOA",
                    "VERSALLES",
                    "VIJES",
                    "YOTOCO",
                    "YUMBO",
                    "ZARZAL"
                ]
            },
            {
                name: "Vaupés",
                city: [
                    "MITU",
                    "CARURU",
                    "PACOA",
                    "TARAIRA",
                    "PAPUNAHUA",
                    "YAVARATE"
                ]
            },
            {
                name: "Vichada",
                city: [
                    "PUERTO CARREÑO",
                    "LA PRIMAVERA",
                    "SANTA ROSALIA",
                    "CUMARIBO"
                ]
            }
        ]
    },
    { name: "Comoras" },
    { name: "Corea del Norte" },
    { name: "Corea del Sur" },
    { name: "Costa de Marfil" },
    { name: "Costa Rica" },
    { name: "Croacia" },
    { name: "Cuba" },
    { name: "Dinamarca" },
    { name: "Dominica" },
    { name: "Ecuador" },
    { name: "Egipto" },
    { name: "El Salvador" },
    { name: "Emiratos Árabes Unidos" },
    { name: "Eritrea" },
    { name: "Eslovaquia" },
    { name: "Eslovenia" },
    { name: "España" },
    { name: "Estados Unidos" },
    { name: "Estonia" },
    { name: "Etiopía" },
    { name: "Filipinas" },
    { name: "Finlandia" },
    { name: "Fiyi" },
    { name: "Francia" },
    { name: "Gabón" },
    { name: "Gambia" },
    { name: "Georgia" },
    { name: "Ghana" },
    { name: "Granada" },
    { name: "Grecia" },
    { name: "Guatemala" },
    { name: "Guyana" },
    { name: "Guinea" },
    { name: "Guinea ecuatorial" },
    { name: "Guinea-Bisáu" },
    { name: "Haití" },
    { name: "Honduras" },
    { name: "Hungría" },
    { name: "India" },
    { name: "Indonesia" },
    { name: "Irak" },
    { name: "Irán" },
    { name: "Irlanda" },
    { name: "Islandia" },
    { name: "Islas Marshall" },
    { name: "Islas Salomón" },
    { name: "Israel" },
    { name: "Italia" },
    { name: "Jamaica" },
    { name: "Japón" },
    { name: "Jordania" },
    { name: "Kazajistán" },
    { name: "Kenia" },
    { name: "Kirguistán" },
    { name: "Kiribati" },
    { name: "Kuwait" },
    { name: "Laos" },
    { name: "Lesoto" },
    { name: "Letonia" },
    { name: "Líbano" },
    { name: "Liberia" },
    { name: "Libia" },
    { name: "Liechtenstein" },
    { name: "Lituania" },
    { name: "Luxemburgo" },
    { name: "Madagascar" },
    { name: "Malasia" },
    { name: "Malaui" },
    { name: "Maldivas" },
    { name: "Malí" },
    { name: "Malta" },
    { name: "Marruecos" },
    { name: "Mauricio" },
    { name: "Mauritania" },
    { name: "México" },
    { name: "Micronesia" },
    { name: "Moldavia" },
    { name: "Mónaco" },
    { name: "Mongolia" },
    { name: "Montenegro" },
    { name: "Mozambique" },
    { name: "Namibia" },
    { name: "Nauru" },
    { name: "Nepal" },
    { name: "Nicaragua" },
    { name: "Níger" },
    { name: "Nigeria" },
    { name: "Noruega" },
    { name: "Nueva Zelanda" },
    { name: "Omán" },
    { name: "Países Bajos" },
    { name: "Pakistán" },
    { name: "Palaos" },
    { name: "Panamá" },
    { name: "Papúa Nueva Guinea" },
    { name: "Paraguay" },
    { name: "Perú" },
    { name: "Polonia" },
    { name: "Portugal" },
    { name: "Reino Unido" },
    { name: "República Centroafricana" },
    { name: "República Checa" },
    { name: "República de Macedonia" },
    { name: "República del Congo" },
    { name: "República Democrática del Congo" },
    { name: "República Dominicana" },
    { name: "República Sudafricana" },
    { name: "Ruanda" },
    { name: "Rumanía" },
    { name: "Rusia" },
    { name: "Samoa" },
    { name: "San Cristóbal y Nieves" },
    { name: "San Marino" },
    { name: "San Vicente y las Granadinas" },
    { name: "Santa Lucía" },
    { name: "Santo Tomé y Príncipe" },
    { name: "Senegal" },
    { name: "Serbia" },
    { name: "Seychelles" },
    { name: "Sierra Leona" },
    { name: "Singapur" },
    { name: "Siria" },
    { name: "Somalia" },
    { name: "Sri Lanka" },
    { name: "Suazilandia" },
    { name: "Sudán" },
    { name: "Sudán del Sur" },
    { name: "Suecia" },
    { name: "Suiza" },
    { name: "Surinam" },
    { name: "Tailandia" },
    { name: "Tanzania" },
    { name: "Tayikistán" },
    { name: "Timor Oriental" },
    { name: "Togo" },
    { name: "Tonga" },
    { name: "Trinidad y Tobago" },
    { name: "Túnez" },
    { name: "Turkmenistán" },
    { name: "Turquía" },
    { name: "Tuvalu" },
    { name: "Ucrania" },
    { name: "Uganda" },
    { name: "Uruguay" },
    { name: "Uzbekistán" },
    { name: "Vanuatu" },
    { name: "Venezuela" },
    { name: "Vietnam" },
    { name: "Yemen" },
    { name: "Yibuti" },
    { name: "Zambia" },
    { name: "Zimbabue" }
];